- name: Telegraf configuration for RabbtiMQ
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "root"
    group: "root"
  with_items:
    - { src: "rabbitmq.conf.j2", dest: "/etc/telegraf/telegraf.d/rabbitmq.conf" }
  tags:
    - telegraf_client-config
  notify:
    - restart telegraf

- name: Add management tag to the monitoring user
  rabbitmq_user:
    user: rabbitmq_monitoring_userid|default('monitoring')
    tags: monitoring,management
    state: present
  run_once: true
