- name: Install scripts to get openstack stats
  copy: src={{ item }} dest=/usr/local/bin/{{ item }} mode=0755
  with_items: "{{ telegraf_openstack_scripts }}"

- name: Telegraf configuration for utility
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "root"
    group: "root"
  with_items:
    - { src: "openstack.conf.j2", dest: "/etc/telegraf/telegraf.d/openstack.conf" }
    - { src: "telegraf.sudo.j2", dest: "/etc/sudoers.d/telegraf" }
  tags:
    - telegraf_client-config
  notify:
    - restart telegraf

